# Generated by Django 3.1.6 on 2021-02-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210204_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/<django.db.models.query_utils.DeferredAttribute object at 0x0000012F0AE93550>'),
        ),
    ]
