# Generated by Django 3.1.6 on 2021-03-31 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210331_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rating_dislikes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='rating_likes',
        ),
    ]
