# Generated by Django 3.1.6 on 2021-03-31 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bookmarkarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookmarkArticle',
        ),
    ]
