# Generated by Django 3.2.2 on 2021-05-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210501_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(choices=[('site_img/1.png', 'лазурит'), ('site_img/2.png', 'лава'), ('site_img/3.png', 'уголь'), ('site_img/4.png', 'обсидиан')], upload_to='', verbose_name='Заглавное изображение'),
        ),
    ]
