# Generated by Django 3.2.2 on 2021-05-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_article_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(null=True, upload_to='code_files/', verbose_name='Файл'),
        ),
    ]
