# Generated by Django 3.2.2 on 2021-06-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_article_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='code_files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(choices=[('site_img/лава.webp', 'лава'), ('site_img/лазурит.webp', 'лазурит'), ('site_img/обсидиан.webp', 'обсидиан'), ('site_img/уголь.webp', 'уголь')], upload_to='', verbose_name='Заглавное изображение'),
        ),
    ]
