# Generated by Django 3.1.6 on 2021-04-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesystem',
            name='action',
            field=models.SmallIntegerField(choices=[(1, 'like'), (-1, 'dislike')]),
        ),
    ]
